import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import Footer from "@/Component/Footer";

const OutfitFont = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Product Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.variable} ${OutfitFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
